// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7pEs45PEr-hWYmmsez03VRNmLBEUmog',
    appId: '1:350444039173:web:96e23fd1e71d922c25c06c',
    messagingSenderId: '350444039173',
    projectId: 'project-6162571745800289827',
    authDomain: 'project-6162571745800289827.firebaseapp.com',
    storageBucket: 'project-6162571745800289827.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtgBzCwvQVRmpuQRykfinB9q-ncDAsw8',
    appId: '1:350444039173:android:be24cdd0a802e93325c06c',
    messagingSenderId: '350444039173',
    projectId: 'project-6162571745800289827',
    storageBucket: 'project-6162571745800289827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcI0EAG-CGoMSsnrXKMEghKUt8Dh3_mpo',
    appId: '1:350444039173:ios:ffbdce23c8e25fca25c06c',
    messagingSenderId: '350444039173',
    projectId: 'project-6162571745800289827',
    storageBucket: 'project-6162571745800289827.appspot.com',
    iosClientId: '350444039173-svttkr0cps7e1b57spakra12fj5sa7q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcI0EAG-CGoMSsnrXKMEghKUt8Dh3_mpo',
    appId: '1:350444039173:ios:ffbdce23c8e25fca25c06c',
    messagingSenderId: '350444039173',
    projectId: 'project-6162571745800289827',
    storageBucket: 'project-6162571745800289827.appspot.com',
    iosClientId: '350444039173-svttkr0cps7e1b57spakra12fj5sa7q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
